drop table if exists admin cascade;
drop table if exists customer cascade;
drop table if exists motherboard cascade;
drop table if exists ordering_product cascade;
drop table if exists ordering cascade;
drop table if exists processor cascade;
drop table if exists product cascade;
drop table if exists ram cascade;
drop table if exists videocard cascade;